export default {
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAIL:'GET_ALL_CATEGORIES_FAIL',
    SET_LOADING:'SET_LOADING',
};